### ISSUE TITLE
Improve javascript code architecture

### ISSUE THREAD

**Issue by maatvirtue** [maatvirtue/WebsiteBase#4]
Improve javascript code architecture so there is less code to write for a specific need and to make the code and architecture of the code much more clear.

Maybe use AngularJS?

**Comment by theprophet31337** [comment]
@Kornagan wrote:
"This is a list of possible technologies.

Frameworks:

AngularJS
Backbone.js
Ember.js
Utilities:

jQuery
Zepto.js
Loaders:

RequireJS
Browserify
Task runners:

Grunt
Gulp
Templating engines:

Way too much, here’s a list (http://engineering.linkedin.com/frontend/client-side-templating-throwdown-mustache-handlebars-dustjs-and-more)"

**Comment by theprophet31337** [comment]
I have an implementation already working with Angular2, jQuery and SystemJS in ES6 (with traceur). I will be pushing it soon :)

Hope that you like it.

**Comment by maatvirtue** [comment]
I am considering Angular2 good enough for now so I will close this issue.
